version: '3.8'

volumes:
    php-fpm-socket:

services:
    php:
        build: ./docker/php
        volumes:
            - type: bind
              source: ./src
              target: /var/www
            - type: volume
              source: php-fpm-socket
              target: /var/run/php-fpm
              volume:
                  nocopy: true
        environment:
            - TZ=Asia/Tokyo

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - type: bind
              source: ./src
              target: /var/www
            - type: bind
              source: ./docker/nginx/default.conf
              target: /etc/nginx/conf.d/default.conf
            - type: volume
              source: php-fpm-socket
              target: /var/run/php-fpm
              volume:
                  nocopy: true
